replicaCount: 1

image:
  repository: vipparlasandeepcharan/bms:v3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik

  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""
